CREATE TABLE Users(
	ID int IDENTITY(1,1) PRIMARY KEY,
	Username nvarchar(100) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[Role] [nvarchar](100) NOT NULL,
);

CREATE TABLE Employees(
	ID int IDENTITY(1,1) PRIMARY KEY,
	Number INT NOT NULL UNIQUE,
	[Name] NVARCHAR(100) NOT NULL,
	[Surname] NVARCHAR(100) NOT NULL,
	Age INT CHECK (Age>=1) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL
);

CREATE TABLE Genres(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    [Name] VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE ProductTypes (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    [Name] VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Artists (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,  
    [Name] VARCHAR(50) NOT NULL UNIQUE
); 

CREATE TABLE Products( 
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(100) NOT NULL, 
	ProdType VARCHAR(50) NOT NULL,
	Genre VARCHAR(100) NOT NULL,
	Artist VARCHAR(100) NOT NULL,
    Quantity INT NOT NULL DEFAULT 0 CHECK (Quantity >= 0), 
	Price SMALLMONEY NOT NULL,
); 

CREATE TABLE Cart(
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    [Name] VARCHAR(100) NOT NULL,
    Quantity INT NOT NULL,
	Price SMALLMONEY NOT NULL,
	Total SMALLMONEY
);


